### PR TITLE
issue 123

### PR DESCRIPTION
**Pull request by SandstormVR**
Added create_repos_for_unit_tests() function that clones basic repos to unit test the builds on it

It clones a repo called mullemeck-unit-tests that has specific versions to unit test mullemeck builds. Test cases can be added in the future

### CODE REVIEW

**Comment by SandstormVR** [comment]
Don't merge it yet, @Isak-P should do the actual testing and/or add new tests or ways to implement the unit test.

**Comment by Isak-P** [comment]
I made every test clone the commits that are relevant for said test, In my opinion it feels cleaner than having a test that simply deletes the repos.

**Comment by Isak-P** [comment]
Looking into why travis is failing

**Comment by Isak-P** [comment]
Travis fails the build with the following message:
module 'jsonschema' has no attribute 'Draft7Validator'.
Is something wrong with Travis? The build works on my machine

**Comment by xobust** [comment]
Seems to be an issue with poetry environment on Travis: 
https://github.com/sdispater/poetry/issues/532

@tonikarppi Could you clean it?

**Comment by tonikarppi** [comment]
I'll change it #171

**Comment by Isak-P** [comment]
Travis says
 [RuntimeError]                                                
 The current Python version (3.6.7) is not supported by the project (^3.7)  
 Please activate a compatible Python version.

**Comment by Isak-P** [comment]
@tonikarppi Will things crash if I update the python version in .travis.yml from 3.6 to 3.7?
It makes travis pass this build, as seen in pull-request #174

**Comment by tonikarppi** [comment]
This will make Docker stop working, but I guess we don't need that.

**Pull request merged**
